// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "../Persona.hpp"


// =====================
// tests para Examen Persona
// ---------------------

TEST_CASE("Ex1", "[Probando constructor default de Fecha]")
{
    Fecha amigo;
    SECTION("Verificando sus atributos default de Fecha")
    {
        REQUIRE(amigo.getDia() == 1);
        REQUIRE(amigo.getMes() == 1);
    }
}

TEST_CASE("Ex2", "[Probando constructor con parametros de Fecha]")
{
    Fecha amigo(-3, 4);
    Fecha amigo2(1,-5);
    SECTION("Verificando creacion con parametros en Fecha")
    {
        REQUIRE(amigo.getMes()==4);
        REQUIRE(amigo.getDia()==1);
        REQUIRE(amigo2.getMes()==1);
    }
}

TEST_CASE("Ex3", "[Probando setters de Fecha]")
{
    Fecha nueva;
    Fecha otra;
    SECTION("Verificando cambios en los atributos de Fecha")
    {
        nueva.setDia(5);
        nueva.setMes(20);
        otra.setDia(32);
        otra.setMes(2);
        REQUIRE(nueva.getDia()==5);
        REQUIRE(nueva.getMes()==1);
        REQUIRE(otra.getDia()==1);
        REQUIRE(otra.getMes()==2);
    }
}

TEST_CASE("Ex4", "[Probando Imprimir]")
{
    Fecha f1(5,6);
    SECTION("Mostrando en consola los datos de la Fecha")
    {
        f1.imprime();
        REQUIRE(true);
    }
}

TEST_CASE("Ex5", "[Probando iguales de Fecha]")
{
    Fecha f1(10,5);
    Fecha f2(1,1);
    Fecha f3;
    SECTION("Probando iguales")
    {
        REQUIRE(f1.iguales(f3)==0);
        REQUIRE(f3.iguales(f2)==1);
    }
}

TEST_CASE("Ex6", "[Constructor Default de Persona]")
{
    Persona c1;
    SECTION("Constructor Default")
    {
        Fecha f1;
        REQUIRE(c1.getNombre()=="amigo");
        REQUIRE(c1.getCumple().iguales(f1)==1);
    }
}

TEST_CASE("Ex7", "[Constructor con parámetros de Caja]")
{
    Persona c2("Goku", Fecha(20,3));
    SECTION("Constructor con parámetros de Persona")
    {
        Fecha f2(20,3);
        REQUIRE(c2.getNombre()=="Goku");
        REQUIRE(c2.getCumple().iguales(f2)==1);
    }
}

TEST_CASE("Ex8", "[Probando setters]")
{
    Fecha f3(23,3);
    Persona c3;
    SECTION("Setters de Persona")
    {
        c3.setNombre("Pikachu");
        c3.setCumple(f3);
        REQUIRE(c3.getNombre()=="Pikachu");
        REQUIRE(c3.getCumple().iguales(f3)==1);
    }
}


TEST_CASE("Ex9", "[Probando imprime de Persona]")
{
    Persona c4;
    SECTION("Imprime de Persona")
    {
        c4.imprime();
        REQUIRE(true);
    }
}